name: Automatic Deployment

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

env:
  NODE_VERSION: 22
  BARE_VERSION: 1.22

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Bare
        run: npm i -g bare@${{ env.BARE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Build & Link
        run: |
          npm run build
          npm link
          npm link noba
      - name: Pretest
        run: npm run pretest
      - name: Test in Node
        run: noba ./tmp/**/*.test.js
      - name: Test in Bare
        run: noba-bare ./tmp/**/*.test.js
  release:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Release
        run: npm run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
