name: Automatic Deployment

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm install
      - name: Build & Link
        run: |
          npm run build
          npm link
      - name: Test
        run: |
          npm run pretest
          noba ./tmp/*.test.js
  release:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm install
      - name: Build & Test the library
        run: npm run build
      - name: Release new sematic version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run ci:release
