name: Publish Wiki

on:
  push:
    branches:
      - develop
    paths:
      - 'wiki/*'
      - '.github/workflows/wiki.yml'

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
